version: "3.9"

services:
  postgres:
    container_name: analisepreditiva-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "!MyStrongPassword"
    volumes:
      - ./data:/var/lib/postgresql/data
  
volumes:
  data:
  mysql:
  